stages:
  - test

variables:
  PYTHON_VERSION: "3.10"

# Configuration globale avant les jobs
before_script:
  - echo "🔧 Préparation de l'environnement Python..."
  - python --version
  - pip install --upgrade pip
  - pip install selenium pytest requests pytest-html

# --- Tests UI ---
test_ui:
  stage: test
  tags:
    - test # 👈 Correspond à ton runner local
  script:
    - echo "🚀 Lancement des tests UI avec Selenium"
    - pytest ui_tests --html=reports/ui_report.html --self-contained-html
  artifacts:
    paths:
      - reports/ui_report.html
    expire_in: 1 week

# --- Tests API ---
test_api:
  stage: test
  tags:
    - test # 👈 Même tag que ton runner
  script:
    - echo "🚀 Lancement des tests API"
    - pytest tests/api --html=reports/api_report.html --self-contained-html
  artifacts:
    paths:
      - reports/api_report.html
    expire_in: 1 week
